---
# https://ansible.readthedocs.io/projects/builder/en/stable/definition/
# https//github.com/ansible/awx-ee/
# https://ansible-builder.readthedocs.io/_/downloads/en/latest/pdf/
version: 3

images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9.3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.9
  ansible_runner:
    package_pip: ansible-runner==2.3.4

  galaxy: _build_v3_py311/requirements.yml
  python: _build_v3_py311/requirements.txt
  system: _build_v3_py311/bindep.txt

#additional_build_files:
#  - src: files/ansible.cfg
#    dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip3 install -U pip wheel setuptools
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    # TODO TEST
    - ENV ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3.9
#  prepend_galaxy:
#    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg