# Source: https://github.com/ansible/awx-ee/blob/devel/execution-environment.yml
# Old version 1 ansible-builder format
# Attention: Might be broken and cannot download collections from ansible-galaxy
# Use newer v3 files
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  galaxy: _build_v1/requirements.yml
  python: _build_v1/requirements.txt
  system: _build_v1/bindep.txt

additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    # Project Receptor is a flexible multi-service relayer with remote execution and
    # orchestration capabilities linking controllers with executors across a mesh of nodes.
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - USER 1000
    - RUN git lfs install