---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: awx.awx
    version: 23.7.0
  - name: community.general
  - name: community.crypto
    version: 2.17.1
  # NetApp
  - name: netapp.aws
  - name: netapp.azure
  - name: netapp.cloudmanager
  - name: netapp.elementsw
  - name: netapp.ontap
    version: 22.9.0
  - name: netapp.storagegrid
  - name: netapp.um_info
    version: 21.8.1